### ISSUE TITLE
revision todo

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/JornadaDroneAnalysis#6]
## writing
- [x] redo figures, "curvature" -> "change rate"
- [x] deal with 30-40% thing in abstract

## manuscript logistics
- [x] cover letter/rebuttal
- [x] track changes manuscript
- [x] zip of all original figures
- [x] zip of latex files
- [ ] new zenodo version (can do this after acceptance)

signed forms from everyone http://downloads.spj.sciencemag.org/remotesensing/License_to_Publish_for_Remote.pdf  
- [x] shawn
- [x] dawn
- [x] feng
- [x] ruben

**Comment by sdtaylor** [comment]
## 2nd revision (accepted w/ minor things)

- [x] new supplement
- [x] response letter as word doc
- [x] fresh primary pdf
- [x] fresh track changes pdf
- [x] fresh latex file

bibtex file and all figures are unchanged from prior submission.
